### Sign up a new user
POST http://localhost:3000/api/v1/auth/sign-up
Content-Type: application/json

{
  "email": "asdfg@asdfg.com",
  "password": "abc123"
}

### Sign in
POST http://localhost:3000/api/v1/auth/sign-in
Content-Type: application/json

{
  "email": "jussaramoreirac@gmail.com",
  "password": "abc123"
}

### Sign up with an existing email
POST http://localhost:3000/api/v1/auth/sign-up
Content-Type: application/json

{
  "email": "jussraramoreirac@gmail.com",
  "password": "abc123"
}

### Sign in with wrong password
POST http://localhost:3000/api/v1/auth/sign-in
Content-Type: application/json

{
  "email": "jussaramoreirac@gmail.com",
  "password": "abc124"
}

### Sign out
POST http://localhost:3000/api/v1/auth/signout

### Get profile
GET http://localhost:3000/api/v1/auth/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0YiIsInVzZXJuYW1lIjoianVzc2FyYW1vcmVpcmFjQGdtYWlsLmNvbSIsImlhdCI6MTY5NzkwNzMzMywiZXhwIjoxNjk3OTA3OTMzfQ.K03avXtOcpN9JjSjMIWpCPasQy-mEc9_CWaQ-v5aWnY
